// This file is automatically generated by build.rs

pub const CAN_BANK_CANISTER_ID: &'static str = "bkyz2-fmaaa-aaaaa-qaaaq-cai";
pub const CAN_HUMANS_CANISTER_ID: &'static str = "be2us-64aaa-aaaaa-qaabq-cai";
pub const CAN_TASKS_CANISTER_ID: &'static str = "br5f7-7uaaa-aaaaa-qaaca-cai";
pub const CAN_VOTINGS_CANISTER_ID: &'static str = "bw4dl-smaaa-aaaaa-qaacq-cai";
pub const CAN_FMJ_CANISTER_ID: &'static str = "bd3sg-teaaa-aaaaa-qaaba-cai";
pub const CAN_ICP_CANISTER_ID: &'static str = "ryjl3-tyaaa-aaaaa-aaaba-cai";
pub const CAN_ROOT_KEY: &'static str = "[48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 131, 200, 129, 35, 122, 214, 225, 17, 52, 51, 238, 75, 208, 111, 197, 94, 71, 225, 123, 67, 101, 209, 149, 57, 208, 215, 209, 11, 191, 153, 231, 250, 241, 43, 248, 105, 41, 83, 8, 165, 209, 214, 70, 38, 225, 239, 57, 84, 25, 199, 198, 102, 225, 245, 161, 206, 217, 24, 94, 250, 129, 33, 15, 172, 71, 186, 37, 86, 61, 108, 134, 251, 224, 194, 163, 117, 252, 186, 8, 182, 84, 51, 14, 170, 72, 149, 146, 206, 202, 219, 44, 238, 254, 54, 136, 179]";
