// This file is automatically generated by build.rs

pub const CAN_BANK_CANISTER_ID: &'static str = "bkyz2-fmaaa-aaaaa-qaaaq-cai";
pub const CAN_HUMANS_CANISTER_ID: &'static str = "be2us-64aaa-aaaaa-qaabq-cai";
pub const CAN_TASKS_CANISTER_ID: &'static str = "br5f7-7uaaa-aaaaa-qaaca-cai";
pub const CAN_VOTINGS_CANISTER_ID: &'static str = "bw4dl-smaaa-aaaaa-qaacq-cai";
pub const CAN_FMJ_CANISTER_ID: &'static str = "bd3sg-teaaa-aaaaa-qaaba-cai";
pub const CAN_ICP_CANISTER_ID: &'static str = "ryjl3-tyaaa-aaaaa-aaaba-cai";
pub const CAN_ROOT_KEY: &'static str = "[48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 143, 54, 110, 237, 55, 52, 85, 52, 86, 176, 108, 96, 85, 85, 171, 102, 165, 67, 107, 27, 78, 68, 219, 145, 63, 18, 147, 89, 27, 29, 246, 162, 36, 67, 209, 168, 90, 9, 8, 198, 81, 163, 35, 132, 28, 157, 29, 205, 19, 100, 231, 224, 117, 187, 117, 139, 36, 59, 160, 248, 33, 136, 98, 238, 161, 110, 172, 122, 144, 171, 160, 253, 202, 107, 195, 200, 49, 225, 25, 73, 251, 130, 163, 25, 123, 22, 29, 221, 24, 28, 147, 233, 152, 92, 58, 86]";
