// This file is automatically generated by build.rs

pub const APP_BANK_CANISTER_ID: &'static str = "c5kvi-uuaaa-aaaaa-qaaia-cai";
pub const APP_HUMANS_CANISTER_ID: &'static str = "c2lt4-zmaaa-aaaaa-qaaiq-cai";
pub const APP_TASKS_CANISTER_ID: &'static str = "ctiya-peaaa-aaaaa-qaaja-cai";
pub const APP_VOTINGS_CANISTER_ID: &'static str = "cuj6u-c4aaa-aaaaa-qaajq-cai";
pub const APP_FMJ_CANISTER_ID: &'static str = "cbopz-duaaa-aaaaa-qaaka-cai";
pub const APP_ICP_CANISTER_ID: &'static str = "ryjl3-tyaaa-aaaaa-aaaba-cai";
pub const APP_ROOT_KEY: &'static str = "[48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 153, 199, 235, 164, 160, 136, 250, 154, 140, 156, 71, 76, 113, 13, 193, 51, 214, 91, 236, 11, 186, 146, 169, 182, 87, 210, 126, 102, 202, 175, 253, 14, 41, 214, 135, 152, 21, 235, 19, 172, 117, 232, 239, 240, 112, 154, 65, 216, 18, 220, 166, 24, 240, 45, 139, 39, 167, 190, 244, 116, 154, 224, 68, 121, 9, 225, 191, 216, 239, 115, 107, 248, 145, 152, 217, 188, 191, 200, 132, 163, 76, 219, 204, 238, 73, 59, 0, 211, 215, 95, 29, 0, 80, 138, 29, 209]";
